spring:
  data:
    mongodb:
      uri: "mongodb://apiuser:password@127.0.0.1/test"

dgs:
  graphql:
    introspection:
      enabled: true
    graphiql:
      enabled: true
    extensions:
      scalars:
        time-dates.enabled: true
        numbers.enabled: true

de.flapdoodle.mongodb.embedded:
  version: "6.0.5"
