de.flapdoodle.mongodb.embedded:
  version: "6.0.5"

dgs:
  graphql:
    introspection:
      enabled: true
    graphiql:
      enabled: true
    extensions:
      scalars:
        time-dates.enabled: true
        numbers.enabled: true